### PR TITLE
Fixed issue #38 (added more sophisticated code optimization)

### PR DESCRIPTION
**Pull request by T-vK**
It's now able to successfully remove multi-line comments and it also gets rid of unnecessary new line characters and more. 
I uploaded a few test files and they ran as expected. I also downloaded them again to confirm that it was working as expected. 

It also minifies variable names btw. I was a bit worried about that at first, but it's only happening to variables that are specifically defined using `local`, so everything fine.

### CODE REVIEW

**Comment by AndiDittrich** [comment]
Dear T-vK,

thanks for your contribution. i think we have to change some details of your pull request first.

generally, i prefer to add a custom option/flag for this kind of optimization/minification because it could may break existing projects (see Semantic Versioning). 

**my suggestion is**

1. to introduce different optimization levels (like gcc) - maybe  `--optimize size` (size only, classic whitespace removing) `--optimize minify` (AST based minification)

2. or add a dedicated `--minify` option for luamin optimization

i would prefer option 1 - what do you think ?

best regards, Andi

**Comment by T-vK** [comment]
How about this:
We add a deprecation message to the `--optimize` flag, but leave it the way it was.
Then we add a `--minify` flag which uses `luamin`. 

I don't think we would need more optimization levels. `luamin` was the only module I could find and I looked at all [176 search results](https://www.npmjs.com/search?q=lua) for `lua`.
Besides that we would have to allow the optimize property in a .nodemcutool file to be either true, false or a string. Certainly possible, but kind of weird. And it could potentially (although unlikely) break other tools that try to parse that file. 

What do _you_ think?

**Comment by AndiDittrich** [comment]
this solution sounds promising :)

could you please modify your pull request/add a new file `LuaMinifier.js` to NodeMCU-Tool which invokes **luamin** ?
i will add the deprecate notice soon

**Comment by T-vK** [comment]
I implemented it. But I think I found another bug #40. Basically `--optimize` doesn't work  unless you put it in the .nodemcutool. Since I implemented `--minify` the exact same way, the same applies to --minify now. 
Both commands work fine when using them in .nodemcutool.

**Comment by AndiDittrich** [comment]
v2.2.0 is out including your pull-request

**Pull request merged**
