### PR TITLE
Add fastupload option

### PR DESCRIPTION
**Pull request by MickaelGuilloux**
I use base64 encoding for uploading files. Then the NodeMCU "encode" module is used for decoding, which is really more efficient.
As the NodeMCU "encode" module is not included by default on the firmware, I have add this as an option, so that the user can choose whether use it or not.

### CODE REVIEW

**Comment by AndiDittrich** [comment]
Thanks Mickael!

i will check it soon

**Comment by AndiDittrich** [comment]
Dear Mickael,

i've decided to **reject your pull request** because i prefer a more generic variant which uses **base64** encoding by default with a fallback to hex. this wont require any config flags and will always choose the fastest available method - this is especially more suitable for beginners.

to achive this, i will replace the `hexWriteHelper` functions with the following generic one (currently working on it)

```lua
-- Regular Version
-- ---------------------

-- Base64 Module available ?
if encoder and encoder.fromBase64 then
    -- Use build-in BASE64 Decoder
    _G.__nmtwrite = function(s) file.write(encoder.fromBase64(s)) end
    print("b")
else
    -- Use classic HEX Decoder
    _G.__nmtwrite = function(s) for c in s:gmatch('..') do file.write(string.char(tonumber(c, 16))) end end
    print("h") 
end
``` 

i hope this is in your intention and it would be great if you like to test/validate the new version.

best regards, Andi

**Comment by AndiDittrich** [comment]
Please try the latest version of the master branch. i've added the base64/hex transfer functions including the [uncompressed code](https://github.com/AndiDittrich/NodeMCU-Tool/blob/master/docs/TransferEncoding.md)

**Comment by MickaelGuilloux** [comment]
Hi Andi,

You are right, your solution is even better and exactly in my intention.
I've just try the latest version of the master branch: it is working fine (both "base64" and "hex" transfert).

For your information, with 23 files for a total size of 32437 bytes, I observe:
- "base64" transfert: 12 seconds
- "hex" transfert: more than 1 minute and a half

Thanks for **NodeMCU-Tool**, it is well written (code is clear and simple) and well documented ! Good job ! 

best regards, Mickaël

**Comment by AndiDittrich** [comment]
Great! **v2.1.0** is out including this feature :)

**Pull request closed without merging**
